services:
  normalizer:
    ports:
      - "9200:9200"
    environment:
      - KAMBI_ACCEPT_WS_ENVELOPE=1
      - KAMBI_NORM_BATCH_MAX=${KAMBI_NORM_BATCH_MAX:-25}
      - KAMBI_NORM_BATCH_FLUSH_MS=${KAMBI_NORM_BATCH_FLUSH_MS:-100}
