services:
  normalizer:
    ports:
      - "9200:9200"
    environment:
      - KAMBI_ACCEPT_WS_ENVELOPE=1
      - KAMBI_NORM_BATCH_MAX=${KAMBI_NORM_BATCH_MAX:-25}
      - KAMBI_NORM_BATCH_FLUSH_MS=${KAMBI_NORM_BATCH_FLUSH_MS:-100}

  collector-kambi-browser-2:
    image: ${COLLECTOR_KAMBI_BROWSER_IMAGE:-ghcr.io/thesamraj/splits-oddsfeed/collector-kambi-browser:latest}
    restart: unless-stopped
    environment:
      - KAMBI_BROWSER_ENABLED=true
      - KAMBI_STATE_HOST=${KAMBI2_STATE_HOST}
      - KAMBI_BRAND=${KAMBI2_BRAND}
      - KAMBI_HTTP_FALLBACK=false
      - KAMBI_NORM_BATCH_MAX=10
      - KAMBI_NORM_BATCH_FLUSH_MS=50
      - REDIS_URL=redis://broker:6379/0
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "${KAMBI2_BROWSER_PORT:-9120}:9118"
