name: collector-kambi-browser

on:
  push:
    branches: ["**"]  # build on any branch
    paths:
      - "collector-kambi-browser/**"
      - ".github/workflows/collector-kambi-browser.yml"
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

concurrency:
  group: collector-kambi-browser-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/${{ github.repository }}/collector-kambi-browser

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Show ref
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"

      - name: List build context
        run: |
          test -f collector-kambi-browser/Dockerfile
          ls -la collector-kambi-browser | sed 's/^/  /'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Auth mode used
        run: |
          if [ -n "${{ secrets.GHCR_PAT }}" ]; then
            echo "mode=PAT" >> $GITHUB_OUTPUT
          else
            echo "mode=GITHUB_TOKEN" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR (PAT)
        if: ${{ secrets.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to GHCR (GITHUB_TOKEN)
        if: ${{ secrets.GHCR_PAT == '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=sha,format=short,prefix=sha-
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=canary,enable={{is_default_branch}}

      - name: Build & push (multi-arch)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./collector-kambi-browser
          file: ./collector-kambi-browser/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          sbom: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Inspect manifest (sha tag preferred)
        run: |
          SHORT="${GITHUB_SHA::7}"
          set -x
          docker buildx imagetools inspect "${IMAGE}:sha-${SHORT}"
