name: collector-kambi-browser
on:
  push:
    branches: [main]
    paths:
      - 'collector-kambi-browser/**'
      - '.github/workflows/collector-kambi-browser.yml'
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  IMAGE: ghcr.io/${{ github.repository }}/collector-kambi-browser
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha

      - uses: docker/build-push-action@v6
        id: build
        with:
          context: ./collector-kambi-browser
          file: ./collector-kambi-browser/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Inspect manifest
        run: |
          SHORT="${GITHUB_SHA::7}"
          docker buildx imagetools inspect "${IMAGE}:sha-${SHORT}"
