name: collector-pinnacle
on:
  push:
    branches: [main]
    paths:
      - 'collector-pinnacle/**'
      - '.github/workflows/collector-pinnacle.yml'
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  IMAGE: ghcr.io/${{ github.repository }}/collector-pinnacle
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      # Prefer PAT if present; otherwise fallback to GITHUB_TOKEN
      - name: Login to GHCR (PAT)
        if: ${{ secrets.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Login to GHCR (GITHUB_TOKEN fallback)
        if: ${{ secrets.GHCR_PAT == '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            # publish :latest only on a tag/release
            type=raw,value=latest,enable={{is_tag}}
      - name: Build & push (multi-arch)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./collector-pinnacle
          file: ./collector-pinnacle/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
      - name: Inspect manifest (short SHA or digest fallback)
        run: |
          SHORT="${GITHUB_SHA::7}"
          set -x
          docker buildx imagetools inspect "${IMAGE}:sha-${SHORT}" || \
            docker buildx imagetools inspect "${{ steps.build.outputs.digest }}"
