name: collector-kambi
on:
  push:
    branches: [main]     # no paths filter to guarantee it runs
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}/collector-kambi

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (PAT fallback)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT \!= '' && secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./collector-kambi
          file: ./collector-kambi/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Inspect sha tag we just pushed
        run: docker buildx imagetools inspect ${{ env.IMAGE }}:sha-${{ github.sha }}
YML < /dev/null
